### ISSUE TITLE
approver do not recieve Email notification when approval task created

### ISSUE THREAD

**Issue by hillbun** [automatiko-io/automatiko-approval-task#3]
I set approvers to email of xxx@xxxx.com

```
                        - name: approvers
                          value:
                            - "xxx@xxxx.com"
```

k8s/kubernetes-email.yml 

```
            - name: QUARKUS_MAILER_FROM
              value: xxx@xxxx.com
            - name: QUARKUS_MAILER_HOST
              value: 12.34.56.78             
            - name: QUARKUS_MAILER_PORT
              value: "25"
            - name: QUARKUS_MAILER_USERNAME
              value: xxx@xxxx.com
            - name: QUARKUS_MAILER_PASSWORD
              value: xxxxxxxxxxxxxx
```

My SMTP server is not tls, just 25 port。

but xxx@xxxx.com do not get email notification when approval task created.

and kubectl logs automatiko-approval-task-7cb9c7764c-gwxzw can not get any info about this.

Please advice.

**Comment by mswiderski** [comment]
you need to add one extra environment variable to active emails see https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/kubernetes-email.yml#L188

Looks like it is missing in readme file. Please let me know if that solved the issue and I will proceed with updating the readme or if you want please update readme yourself and send PR, contributions more than welcome :)

**Comment by hillbun** [comment]
Yes, I have these lines in k8s/kubernetes-email.yml

```
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_OPERATOR_SDK_NAMESPACES
              value: default
            - name: QUARKUS_AUTOMATIKO_SERVICE_URL
              value: http://automatiko-approval-task.default/
            - name: QUARKUS_MAILER_FROM
              value: xxx@xxx.com
            - name: QUARKUS_MAILER_HOST
              value: 12.34.56.78
            - name: QUARKUS_MAILER_PORT
              value: "25"
            - name: QUARKUS_MAILER_USERNAME
              value: xxx@xxx.com
            - name: QUARKUS_MAILER_PASSWORD
              value: xxxxxxxxxxx
            - name: QUARKUS_PROFILE
              value: withemail
```
