### ISSUE TITLE
email notification templates customization request

### ISSUE THREAD

**Issue by hillbun** [automatiko-io/automatiko-approval-task#4]
I need to customize email notification templates, such as title, body

**Comment by mswiderski** [comment]
this one depends on change in automatiko https://github.com/automatiko-io/automatiko-engine/issues/280

**Comment by mswiderski** [comment]
the work is pretty much done, if you want to give it a try before it gets officially released
(as it requires new release of automatiko - due by the end of next week) then try with this image `mswiderski/automatiko-approval-task:0.4.0`

Documentation how to make use of it is here: https://github.com/automatiko-io/automatiko-approval-task#customize-email-templates

**Comment by hillbun** [comment]
where is the demo of approval-email.html?

**Comment by mswiderski** [comment]
Here is the default email template https://github.com/automatiko-io/automatiko-approval-task/blob/main/src/main/resources/templates/approval-email.html

**Comment by mswiderski** [comment]
I plan to release Automatiko tomorrow and then approval task 0.4.0. 
have you tried to use custom email template?

**Comment by hillbun** [comment]
which tag of image should I use to try and test?

**Comment by mswiderski** [comment]
> which tag of image should I use to try and test?

https://github.com/automatiko-io/automatiko-approval-task/issues/4#issuecomment-1221032269

**Comment by hillbun** [comment]
I get env inside pod of automatiko-approval-task

QUARKUS_AUTOMATIKO_TEMPLATES_FOLDER=/templates

but approve email body contents do not match  /templates/approval-email.html , it is still default templates.

also I need to  customize email title.

**Comment by mswiderski** [comment]
and you paste the config map you use (the actual content of the values are not important) just the structure of the config map. Then how it is mapped to the deployment so paste the deployment manifest as well.

When it comes to customise the email subject, I will look into it how it can be done.

**Comment by hillbun** [comment]
I mean cat /templates/approval-email.html 

I customize:

<h2 style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; font-family: 'Lato', sans-serif; margin-top: 0; color: #000; font-size: 40px; margin-bottom: 0; font-weight: 400; line-height: 1.4;">Pipeline awaits approval - ABC.COM</h2>

But the email recieved, is Pipeline awaits approval

**Comment by mswiderski** [comment]
but how do you provide this template to the pod? It should be done via config map and then volume mapped to the deployment, have you done that?

**Comment by hillbun** [comment]
```
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: QUARKUS_OPERATOR_SDK_NAMESPACES
          value: default
        - name: QUARKUS_AUTOMATIKO_SERVICE_URL
          value: http://automatiko-approval-task.default/
        - name: QUARKUS_MAILER_FROM
          value: xxxx
        - name: QUARKUS_MAILER_HOST
          value: xx
        - name: QUARKUS_MAILER_PORT
          value: "25"
        - name: QUARKUS_MAILER_USERNAME
          value: xxx
        - name: QUARKUS_MAILER_PASSWORD
          value: xxxx
        - name: QUARKUS_PROFILE
          value: withemail
        - name: QUARKUS_MAILER_START_TLS
          value: DISABLED
        - name: QUARKUS_AUTOMATIKO_TEMPLATES_FOLDER
          value: /templates
        image: automatiko/automatiko-approval-task
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: automatiko-approval-task
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /templates
          name: templates-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: automatiko-approval-task
      serviceAccountName: automatiko-approval-task
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: approval-task-templates
        name: templates-volume
```

**Comment by mswiderski** [comment]
you are using wrong image `image: automatiko/automatiko-approval-task` it should be `image: mswiderski/automatiko-approval-task:0.4.0` as only the one from my repo has the latest changes.

Plus, how does the config map looks like - named `approval-task-templates`? What entires does it have?

**Comment by hillbun** [comment]
it is  ok now.

**Comment by mswiderski** [comment]
so now the email template is taken from config map, right? 

and last remaining issue is the email subject? Is there anything else you need to customise there?

**Comment by hillbun** [comment]
I need to pass task params to email subject

**Comment by mswiderski** [comment]
what parameters are required there?

**Comment by hillbun** [comment]
```
                    - name: deploy-dev-approval-task
                      taskRef:
                        apiVersion: tekton.automatiko.io/v1alpha1
                        kind: ApprovalTask
                        name: approvaltask
                      params:
                        - name: pipeline                                                                                                                    
                          value: "$(context.pipelineRun.name)"                                                                                              
                        - name: description                                                                                                                 
                          value: "Approval from pipeline $(context.pipeline.name)"                                                                          
                        - name: approvers                                                                                                                   
                          value:                                                                                                                            
                            - "xxx@xx.com" 
                        - name: foo
                          value:  "bar"
```

I set foo in task

**Comment by mswiderski** [comment]
you can use the 0.4.0 from mswiderski repo to try out to customise the email subject as well. 

Fist and foremost is to apply the CRD from here https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/approvaltasks.tekton.automatiko.io-v1.yml as there are new spec item introduced. 

Then you can use these instructions to override default email subject https://github.com/automatiko-io/automatiko-approval-task#customize-email-templates

**Comment by hillbun** [comment]
I suggest customize email subject

````
- name: APPROVAL_TASK_EMAIL_SUBJECT
  value: "Here is an approval for {pipeline} waiting to be deployed to {environment}" 
````

move from  automatiko-approval-task deployment environment to approval task params

**Comment by hillbun** [comment]
```
kubectl apply -f https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/approvaltasks.tekton.automatiko.io-v1.yml
error: error parsing https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/approvaltasks.tekton.automatiko.io-v1.yml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context
```

**Comment by mswiderski** [comment]
> I suggest customize email subject
> 
> ```
> - name: APPROVAL_TASK_EMAIL_SUBJECT
>   value: "Here is an approval for {pipeline} waiting to be deployed to {environment}" 
> ```
> 
> move from automatiko-approval-task deployment environment to approval task params

and how about already using the `description` param instead? Then there won't be any need to include new params. Though it will only allow you to reference context data from Tekton like `"Approval from pipeline $(context.pipeline.name)"`

all the variables will be directly expended to values by Tekton. Would this work for you?

**Comment by mswiderski** [comment]
> kubectl apply -f https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/approvaltasks.tekton.automatiko.io-v1.yml
> error: error parsing https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/approvaltasks.tekton.automatiko.io-v1.yml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context

very weird as this line has not changed at all. Could you first remove the previous version and start from scratch?

**Comment by hillbun** [comment]
description param is ok to email sunject.

and approvaltasks.tekton.automatiko.io-v1.yml: upate ok now.

**Comment by mswiderski** [comment]
excellent, so I will never the need for the extended CRD and extra environment variable and rely on description.

Very good feedback @hillbun !!!

**Comment by mswiderski** [comment]
alright, new version of 0.4.0 is now pushed to mswiderski repo. Please take it for a test drive. Once you verify it does what is needed I will work on preparing releases so it will be ready in the official repo in a day or two.

**Comment by hillbun** [comment]
Yes, all tests pass

**Comment by hillbun** [comment]
in approval-email.html 

```
<p style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"><a href="{link}" class="btn btn-primary" style="-ms-text-size-a
djust: 100%; -webkit-text-size-adjust: 100%; text-decoration: none; padding: 10px 15px; display: inline-block; border-radius: 5px; background: #007bff; color: #ffffff;">Go to
 approval task</a></p>
```

I need to customize {link} , how to?

**Comment by mswiderski** [comment]
what do you mean by customise the link? Link is generated be the backend to ensure it can point to a valid task with proper credentials

**Comment by hillbun** [comment]
current link is

`http://localhost:8080/management/tasks/link/c2luZ2xlfGQ1ZTVlY2VmLTY0MWQtMzk1MC05MTYyLTYzY2NkMWQzYjE2MjphODFkMjhlOS0zOWU5LTQxMTgtYjkxNS1iNjFmNTRmMzQ2Y2N8ODQ2NTM0MWYtNDJlYi00M2EyLTk0ZmYtOWQxZTk4NDYyOGUwfDQ5NTQyODg3NkBxcS5jb20=`

I need to replace http://localhost:8080/ with env below, so I can click and visit what UI

            - name: QUARKUS_AUTOMATIKO_APPROVAL_URL
              value: http://automatiko-approval.xxxxx.com/

**Comment by mswiderski** [comment]
that is already there, you need to set it via env variable of the deployment:

````
- name: QUARKUS_AUTOMATIKO_SERVICE_URL
  value: http://automatiko-approval.xxxxx.com
````

**Comment by hillbun** [comment]
My setting is 

```
            - name: QUARKUS_AUTOMATIKO_SERVICE_URL
              value: http://automatiko-approval-task.default/
```

This is just for k8s internal service only, and email link is http://localhost:8080/  but not http://automatiko-approval-task.default/

I think we should add another env 

```
- name: QUARKUS_AUTOMATIKO_SERVICE_URL
  value: http://automatiko-approval.xxxxx.com
```

for email link point to ingress domain name.

**Comment by mswiderski** [comment]
`QUARKUS_AUTOMATIKO_SERVICE_URL` is to point to the ingress domain name as it is then allowing to access service from outside y users.

I just double checked and it is properly set, I use this setup https://github.com/automatiko-io/automatiko-approval-task/blob/main/k8s/kubernetes-basic.yml#L183 as I am running through port forward and I see in the mail link like this:

`<a href="http://localhost:9000/management/tasks/link/c2luZ2xlfGQ`

so there must be some kind of type or so that does not get properly resolved.

**Comment by hillbun** [comment]
do u mean QUARKUS_AUTOMATIKO_SERVICE_URL  is just used for outside visit only?

and not for any inside calls?

If I set QUARKUS_AUTOMATIKO_SERVICE_URL  to http://automatiko-approval.xxxxx.com/ , the link in email will be http://automatiko-approval.xxxxx.com/ and not http://localhost:8080/ ?

I will trt it now

**Comment by mswiderski** [comment]
exactly that

**Comment by hillbun** [comment]
I set QUARKUS_AUTOMATIKO_SERVICE_URL:       http://automatiko-approval.xxxx.com/

but link in email is still http://localhost:8080/

please advise

**Comment by mswiderski** [comment]
where do you set it? In the pipeline or in the deployment? Can you paste the deployment yaml here?

**Comment by hillbun** [comment]
```
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: QUARKUS_OPERATOR_SDK_NAMESPACES
          value: default
        - name: QUARKUS_AUTOMATIKO_SERVICE_URL
          value: http://automatiko-approval.xxxx.com/
...
        image: mswiderski/automatiko-approval-task:0.4.0
```
