### ISSUE TITLE
automatiko-approval-task container cant start cause it needs to run as root

### ISSUE THREAD

**Issue by quinyx-max** [automatiko-io/automatiko-approval-task#9]
eks: 1.25
tekton-pipelines: 0.48.0
tekton-dashboard: 0.35.0
tekton-triggers: 0.24.0

after adding these to the kubernetes-oath.yml for each container, to get the replicaset to continue, 
```yaml
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: 
      - ALL
  seccompProfile:
    type: "RuntimeDefault"
```
i got this error when describing the `automatiko-approval-task` pod
`Warning  Failed     9s (x6 over 46s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "automatiko-approval-task-6c99458dc4-6fxkq_tekton-pipelines(b2555ca7-25f3-4355-816d-3d58a131ef3f)", container: automatiko-approval-task)`

i dont want to lower the podsecurity on the cluster, is there any other way to make it work or fix it?
